#!/usr/bin/env python3
"""
installer.py — YouAI Digital Twin Installer
=============================================
Standalone setup tool that prepares the environment for YouAI.
Run this ONCE before launching Start.py for the first time.

This script does NOT modify any source files or connect to the AI.

Usage:
    python installer.py              # Full install
    python installer.py --check      # Check environment only (no install)
    python installer.py --venv       # Create virtual environment and install
"""

import os
import sys
import subprocess
import platform
import shutil
import time
from pathlib import Path

# ── ANSI Colors ─────────────────────────────────────────────────────────────
def supports_color() -> bool:
    return hasattr(sys.stdout, "isatty") and sys.stdout.isatty()

_USE_COLOR = supports_color()

def _c(code: str) -> str:
    return f"\033[{code}m" if _USE_COLOR else ""

RESET   = _c("0")
BOLD    = _c("1")
DIM     = _c("2")
GREEN   = _c("92")
YELLOW  = _c("93")
RED     = _c("91")
CYAN    = _c("96")
MAGENTA = _c("95")
WHITE   = _c("97")

# ── Constants ────────────────────────────────────────────────────────────────
MIN_PYTHON  = (3, 10)
PROJECT_ROOT = Path(__file__).resolve().parent
REQUIREMENTS = PROJECT_ROOT / "requirements.txt"
VENV_DIR     = PROJECT_ROOT / "venv"

REQUIRED_DIRS = [
    PROJECT_ROOT / "logs",
    PROJECT_ROOT / "Backend" / "data",
    PROJECT_ROOT / "Backend" / "memory",
]

ENV_TEMPLATE_SRC = PROJECT_ROOT / "Backend" / "memory" / ".env.memory"
ENV_EXAMPLE = """# YouAI Memory Encryption Key
# This file is auto-generated on first run.
# DO NOT share this file — it protects your encrypted memory database.
# MEMORY_ENCRYPTION_KEY=<auto-generated on first launch>
"""

# ── Packages to verify after install ────────────────────────────────────────
VERIFY_IMPORTS = [
    ("PyQt6",           "PyQt6"),
    ("pyttsx3",         "pyttsx3"),
    ("speech_recognition", "speech_recognition"),
    ("gtts",            "gtts"),
    ("pygame",          "pygame"),
    ("pyperclip",       "pyperclip"),
    ("pyautogui",       "pyautogui"),
    ("mss",             "mss"),
    ("cv2",             "opencv-python"),
    ("numpy",           "numpy"),
    ("cryptography",    "cryptography"),
    ("dotenv",          "python-dotenv"),
    ("httpx",           "httpx"),
    ("PIL",             "Pillow"),
    ("comtypes",        "comtypes"),
    ("browser_cookie3", "browser_cookie3"),
]


# ── Utility Functions ────────────────────────────────────────────────────────

def banner():
    width = 62
    print(f"\n{BOLD}{CYAN}{'═' * width}{RESET}")
    print(f"{BOLD}{WHITE}  {'YouAI Digital Twin — Installer':^{width - 4}}{RESET}")
    print(f"{BOLD}{CYAN}{'═' * width}{RESET}")
    print(f"{DIM}  Version: 1.0  |  Platform: {platform.system()} {platform.release()}{RESET}")
    print(f"{BOLD}{CYAN}{'─' * width}{RESET}\n")


def check_mark(ok: bool) -> str:
    return f"{GREEN}✔{RESET}" if ok else f"{RED}✘{RESET}"


def step(label: str, width: int = 52) -> None:
    print(f"  {CYAN}•{RESET} {label:<{width}}", end="", flush=True)


def ok(msg: str = "OK") -> None:
    print(f" {GREEN}{msg}{RESET}")


def warn(msg: str) -> None:
    print(f" {YELLOW}{msg}{RESET}")


def fail(msg: str) -> None:
    print(f" {RED}{msg}{RESET}")


def section(title: str) -> None:
    print(f"\n{BOLD}{MAGENTA}▶  {title}{RESET}")
    print(f"{DIM}{'─' * 56}{RESET}")


# ── Check Steps ──────────────────────────────────────────────────────────────

def check_python() -> bool:
    """Verify Python version meets minimum requirements."""
    section("Python Version Check")
    version = sys.version_info
    step(f"Python {version.major}.{version.minor}.{version.micro}")
    if version >= MIN_PYTHON:
        ok(f"(required: {MIN_PYTHON[0]}.{MIN_PYTHON[1]}+)")
        return True
    else:
        fail(f"(required: {MIN_PYTHON[0]}.{MIN_PYTHON[1]}+)  ← Please upgrade!")
        return False


def check_pip() -> bool:
    """Verify pip is available."""
    section("pip Check")
    step("pip availability")
    try:
        result = subprocess.run(
            [sys.executable, "-m", "pip", "--version"],
            capture_output=True, text=True
        )
        if result.returncode == 0:
            version_line = result.stdout.strip().split("\n")[0]
            ok(version_line)
            return True
        fail("not found")
        return False
    except Exception as e:
        fail(f"error: {e}")
        return False


def create_directories() -> None:
    """Create required runtime directories if they don't exist."""
    section("Creating Required Directories")
    for d in REQUIRED_DIRS:
        step(str(d.relative_to(PROJECT_ROOT)))
        if d.exists():
            ok("already exists")
        else:
            d.mkdir(parents=True, exist_ok=True)
            ok("created")


def create_env_template() -> None:
    """Create .env.memory template if it doesn't already exist."""
    section("Environment File Setup")
    step("Backend/memory/.env.memory")
    if ENV_TEMPLATE_SRC.exists():
        ok("already exists")
    else:
        ENV_TEMPLATE_SRC.write_text(ENV_EXAMPLE, encoding="utf-8")
        ok("template created")


def install_requirements() -> dict:
    """Install all packages from requirements.txt. Returns {pkg: ok/fail}."""
    section("Installing Dependencies")

    if not REQUIREMENTS.exists():
        fail(f"requirements.txt not found at {REQUIREMENTS}")
        return {}

    step(f"Installing from {REQUIREMENTS.name}")
    print()  # newline for subprocess output

    result = subprocess.run(
        [sys.executable, "-m", "pip", "install", "-r", str(REQUIREMENTS), "--quiet"],
        capture_output=False,
        text=True,
    )

    if result.returncode == 0:
        print(f"\n  {GREEN}All packages installed successfully.{RESET}")
    else:
        print(f"\n  {RED}Some packages may have failed. Check output above.{RESET}")

    return {"pip_install": result.returncode == 0}


def verify_imports() -> dict:
    """Test-import each required package and report results."""
    section("Verifying Package Imports")

    results = {}
    for module_name, pkg_name in VERIFY_IMPORTS:
        step(f"{pkg_name}")
        try:
            __import__(module_name)
            ok()
            results[pkg_name] = True
        except ImportError:
            fail("MISSING — run: pip install " + pkg_name)
            results[pkg_name] = False

    return results


def create_venv() -> bool:
    """Create a virtual environment at project_root/venv."""
    section("Creating Virtual Environment")
    step(f"Creating venv at {VENV_DIR.name}/")
    if VENV_DIR.exists():
        ok("already exists")
        return True
    try:
        subprocess.run([sys.executable, "-m", "venv", str(VENV_DIR)], check=True)
        ok("created")
        return True
    except subprocess.CalledProcessError as e:
        fail(f"failed: {e}")
        return False


def print_summary(checks: dict) -> None:
    """Print a final colored summary of all checks."""
    width = 62
    print(f"\n{BOLD}{CYAN}{'═' * width}{RESET}")
    print(f"{BOLD}{WHITE}  {'Installation Summary':^{width - 4}}{RESET}")
    print(f"{BOLD}{CYAN}{'─' * width}{RESET}")

    passed = sum(1 for v in checks.values() if v)
    total  = len(checks)

    for label, ok_flag in checks.items():
        mark = check_mark(ok_flag)
        status = f"{GREEN}PASS{RESET}" if ok_flag else f"{RED}FAIL{RESET}"
        print(f"  {mark} {label:<44} {status}")

    pct = int(passed / max(total, 1) * 100)
    color = GREEN if pct >= 90 else YELLOW if pct >= 60 else RED
    print(f"\n{BOLD}{CYAN}{'─' * width}{RESET}")
    print(f"  {color}{passed}/{total} checks passed ({pct}%){RESET}")

    if passed == total:
        print(f"\n  {BOLD}{GREEN}✔  YouAI is ready to launch!{RESET}")
        print(f"  {DIM}Run:  python Start.py{RESET}")
    else:
        print(f"\n  {YELLOW}⚠  Some checks failed. Review the errors above.{RESET}")
        print(f"  {DIM}Try:  pip install -r requirements.txt{RESET}")

    print(f"{BOLD}{CYAN}{'═' * width}{RESET}\n")


# ── Entry Point ──────────────────────────────────────────────────────────────

def main():
    args       = sys.argv[1:]
    check_only = "--check" in args
    use_venv   = "--venv"  in args

    banner()

    all_checks = {}

    # 1. Python version
    all_checks["Python >= 3.10"] = check_python()
    if not all_checks["Python >= 3.10"]:
        print(f"\n{RED}Cannot continue: Python version is too old.{RESET}\n")
        sys.exit(1)

    # 2. pip
    all_checks["pip available"] = check_pip()

    if not check_only:
        # 3. Directories
        create_directories()

        # 4. .env.memory template
        create_env_template()

        # 5. Optional venv
        if use_venv:
            all_checks["Virtual environment"] = create_venv()

        # 6. Install packages
        install_results = install_requirements()
        all_checks.update(install_results)

    # 7. Verify imports
    import_results = verify_imports()
    for pkg, status in import_results.items():
        all_checks[pkg] = status

    # 8. Summary
    print_summary(all_checks)


if __name__ == "__main__":
    main()
